name: Terraform Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'
      - '.github/workflows/terraform-plan-apply.yml'
  push:
    branches:
      - main
    paths:
      - '**.tf'
      - '.github/workflows/terraform-plan-apply.yml'

env:
  TF_VAR_billing_account: ${{ vars.BILLING_ACCOUNT }}
  TF_VAR_org_id: ${{ vars.ORG_ID }}
  GCP_BUCKET_PREFIX: ${{ vars.GCP_BUCKET_PREFIX }}
  GCP_BUCKET: ${{ vars.GCP_BUCKET }}

jobs:
  terraform:
    uses: mtopps/github-workflow/.github/workflows/terraform-plan-apply.yml@main
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER_NAME: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
      GCP_WORKLOAD_IDENTITY_SA_EMAIL: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}