name: Test workflow

on:
  workflow_call:
    inputs:
      GCP_BUCKET_PREFIX:
        required: true
        type: string
      GCP_BUCKET:
        required: true
        type: string
    secrets:
        GCP_WORKLOAD_IDENTITY_PROVIDER_NAME:
            required: true
        GCP_WORKLOAD_IDENTITY_SA_EMAIL:
            required: true


jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "BILLING_ACCOUNT=${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "ORG_ID=${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "GCP_WORKLOAD_IDENTITY_PROVIDER_NAME=${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}" >> $GITHUB_ENV
          echo "GCP_WORKLOAD_IDENTITY_SA_EMAIL=${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}" >> $GITHUB_ENV
          echo $GITHUB_ENV