name: Test workflow

on:
  workflow_call:
    inputs:
      GCP_BUCKET_PREFIX:
        required: true
        type: string
      GCP_BUCKET:
        required: true
        type: string

permissions:
    contents: read
    id-token: write
    pull-requests: write

jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
            - name: Set Environment Variables
              run: |
                echo "${{ inputs.env_vars }}" >> $GITHUB_ENV