name: Terraform Workflow

on:
  workflow_call:
    inputs:
      GCP_BUCKET_PREFIX:
        required: true
        type: string
      GCP_BUCKET:
        required: true
        type: string
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER_NAME:
        required: true
      GCP_WORKLOAD_IDENTITY_SA_EMAIL:
        required: true
      TOKEN:
        required: false
      OWNER:
        required: false

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Set Environment Variables
        run: |

          # Set TF_VAR environment variables
          echo "TF_VAR_token=${{ secrets.TOKEN }}" >> $GITHUB_ENV
          echo "TF_VAR_owner=${{ secrets.OWNER }}" >> $GITHUB_ENV
          echo "TF_VAR_GCP_WORKLOAD_IDENTITY_PROVIDER_NAME=${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}" >> $GITHUB_ENV
          echo "TF_VAR_GCP_WORKLOAD_IDENTITY_SA_EMAIL=${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}" >> $GITHUB_ENV

      - name: Debug Info
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Paths: ${{ github.event.pull_request.changed_files }}"
          echo "GCP_WORKLOAD_IDENTITY_PROVIDER_NAME: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}"
          echo "GCP_WORKLOAD_IDENTITY_SA_EMAIL: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}"
          echo "GCP_BUCKET_PREFIX: ${{ inputs.GCP_BUCKET_PREFIX }}"
          echo "GCP_BUCKET: ${{ inputs.GCP_BUCKET }}"
          echo "TF_VAR_token: ${{ env.TF_VAR_token }}"
          echo "TF_VAR_owner: ${{ env.TF_VAR_owner }}"
          echo "TF_VAR_GCP_WORKLOAD_IDENTITY_PROVIDER_NAME: ${{ env.TF_VAR_GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}"
          echo "TF_VAR_GCP_WORKLOAD_IDENTITY_SA_EMAIL: ${{ env.TF_VAR_GCP_WORKLOAD_IDENTITY_SA_EMAIL }}"

      - uses: actions/checkout@v4.1.7

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2.1.5'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}

      - name: Verify Authentication
        run: gcloud auth list

      - uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.9.5

      - id: init
        name: Terraform Init
        run: terraform init -lockfile=readonly -input=false -backend-config="prefix=${{ inputs.GCP_BUCKET_PREFIX }}" -backend-config="bucket=${{ inputs.GCP_BUCKET }}"

      - id: validate
        name: Terraform Validate
        run: terraform validate -no-color

      - id: plan
        name: Terraform Plan
        run: |
          echo "Running Terraform Plan with detailed logging..."
          terraform plan -no-color -out=tfplan -input=false -detailed-exitcode 2>&1 | tee terraform_plan.log
        continue-on-error: true

      - name: Upload Plan
        uses: actions/upload-artifact@v4.4.0
        with:
          name: tfplan
          path: tfplan

      - name: Upload Terraform Plan Log
        uses: actions/upload-artifact@v4.4.0
        with:
          name: terraform_plan_log
          path: terraform_plan.log