name: Tfsec Checks on Terraform Code

on:
  workflow_call:

permissions: read-all

jobs:
  tfsec-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git Repository
        uses: 'actions/checkout@v4.1.7'

      - name: Run Tfsec Checks
        uses: 'aquasecurity/tfsec-action@v1.0.3'
        with:
            soft_fail: true
            github_token: ${{ secrets.GITHUB_TOKEN }}


